create table public."Categoria_mp" (
  id bigint generated by default as identity not null,
  nombre character varying not null,
  unidad character varying not null,
  fc bigint not null,
  constraint Categoria_mp_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Categoria_producto" (
  id bigint generated by default as identity not null,
  nombre character varying(255) not null,
  "conCaducidad" boolean not null,
  constraint Categoria_producto_pkey primary key (id),
  constraint Categoria_producto_id_key unique (id)
) TABLESPACE pg_default;

create table public."Compras" (
  id bigint generated by default as identity not null,
  "id_Proveedor" bigint null,
  id_mp bigint null,
  total double precision not null,
  fecha timestamp without time zone not null,
  "id_Usuario" bigint null,
  constraint Compras_pkey primary key (id),
  constraint Compras_id_Proveedor_fkey foreign KEY ("id_Proveedor") references "Proveedores" (id),
  constraint Compras_id_Usuario_fkey foreign KEY ("id_Usuario") references "Usuarios" (id),
  constraint Compras_id_mp_fkey foreign KEY (id_mp) references "Materia_prima" (id)
) TABLESPACE pg_default;

create table public."Materia_prima" (
  id bigint generated by default as identity not null,
  nombre character varying not null,
  "id_Categoria_mp" bigint not null,
  stock bigint not null,
  fecha_creacion date not null,
  "seVende" boolean null default false,
  "siVendePrecio" double precision null,
  constraint Materia_prima_pkey primary key (id),
  constraint Materia_prima_id_key unique (id),
  constraint Materia_prima_id_Categoria_mp_fkey foreign KEY ("id_Categoria_mp") references "Categoria_mp" (id)
) TABLESPACE pg_default;

create table public."Productos" (
  id bigint generated by default as identity not null,
  nombre character varying(255) not null,
  precio double precision not null,
  stock bigint not null,
  caducidad date null,
  "id_Categoria_producto" bigint not null,
  "id_Usuario" bigint null,
  "id_Receta" integer null,
  constraint Productos_pkey primary key (id),
  constraint Productos_id_Categoria_producto_fkey foreign KEY ("id_Categoria_producto") references "Categoria_producto" (id),
  constraint Productos_id_Receta_fkey foreign KEY ("id_Receta") references "Receta" (id),
  constraint Productos_id_Usuario_fkey foreign KEY ("id_Usuario") references "Usuarios" (id)
) TABLESPACE pg_default;

create table public."Proveedores" (
  id bigint generated by default as identity not null,
  nombre character varying(255) not null,
  direccion character varying(255) not null,
  telefono bigint not null,
  "id_Categoria_p" bigint not null,
  email character varying null,
  horario character varying null,
  hora_apertura time without time zone null,
  hora_cierre time without time zone null,
  constraint Proveedores_pkey primary key (id),
  constraint Proveedores_id_key unique (id),
  constraint Proveedores_id_Categoria_p_fkey foreign KEY ("id_Categoria_p") references "Categoria_producto" (id)
) TABLESPACE pg_default;

create table public."Receta" (
  id serial not null,
  "ids_Mps" bigint[] null,
  cantidades bigint[] not null,
  constraint recetas_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Tipo_Usuario" (
  id bigint generated by default as identity not null,
  nombre character varying(255) not null,
  descripcion character varying(255) not null,
  constraint Tipo_Usuario_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Usuarios" (
  id bigint generated by default as identity not null,
  nombre character varying not null,
  password character varying not null,
  tipo bigint not null,
  fecha_creacion date not null,
  constraint Usuarios_pkey primary key (id),
  constraint Usuarios_tipo_fkey foreign KEY (tipo) references "Tipo_Usuario" (id)
) TABLESPACE pg_default;

create table public."Ventas" (
  id bigint generated by default as identity not null,
  "id_Productos" bigint[] not null,
  total double precision not null,
  fecha timestamp without time zone not null,
  pago double precision not null,
  cambio double precision not null,
  "id_Usuario" bigint not null,
  "id_mp_seVende" bigint null,
  constraint Ventas_pkey primary key (id),
  constraint Ventas_id_key unique (id),
  constraint Ventas_id_Usuario_fkey foreign KEY ("id_Usuario") references "Usuarios" (id),
  constraint Ventas_id_mp_seVende_fkey foreign KEY ("id_mp_seVende") references "Materia_prima" (id)
) TABLESPACE pg_default;