create table public."Categoria_mp" (
  id bigint generated by default as identity not null,
  nombre character varying not null,
  "conCaducidad" boolean null default false,
  constraint Categoria_mp_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Categoria_producto" (
  id bigint generated by default as identity not null,
  nombre character varying(255) not null,
  "conCaducidad" boolean not null,
  constraint Categoria_producto_pkey primary key (id),
  constraint Categoria_producto_id_key unique (id)
) TABLESPACE pg_default;

create table public."Compras" (
  id bigint generated by default as identity not null,
  "id_Proveedor" bigint null,
  id_mp bigint null,
  total double precision not null,
  fecha timestamp without time zone not null,
  "id_Usuario" bigint null,
  constraint Compras_pkey primary key (id),
  constraint Compras_id_Proveedor_fkey foreign KEY ("id_Proveedor") references "Proveedores" (id),
  constraint Compras_id_Usuario_fkey foreign KEY ("id_Usuario") references "Usuarios" (id),
  constraint Compras_id_mp_fkey foreign KEY (id_mp) references "Materia_prima" (id)
) TABLESPACE pg_default;

create table public."Corte_inventario" (
  id bigint generated by default as identity not null,
  inicio_corte time without time zone not null,
  fin_corte time without time zone null,
  ids_mps bigint[] null,
  fecha_corte date not null default CURRENT_DATE,
  estado text not null default 'iniciado'::text,
  stock_inicial bigint[] null,
  stock_final bigint[] null,
  constraint Corte_inventario_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Materia_prima" (
  id bigint generated by default as identity not null,
  nombre character varying not null,
  "id_Categoria_mp" bigint not null,
  stock bigint not null,
  fecha_creacion date null,
  "seVende" boolean null default false,
  "siVendePrecio" double precision null,
  caducidad date null,
  constraint Materia_prima_pkey primary key (id),
  constraint Materia_prima_id_key unique (id),
  constraint Materia_prima_id_Categoria_mp_fkey foreign KEY ("id_Categoria_mp") references "Categoria_mp" (id)
) TABLESPACE pg_default;

create table public."Productos" (
  id bigint generated by default as identity not null,
  nombre character varying(255) not null,
  precio double precision not null,
  "id_Categoria_producto" bigint not null,
  "id_Usuario" bigint null,
  "id_Receta" integer null,
  tamaño character varying null,
  stock bigint null,
  fecha_caducidad date null,
  constraint Productos_pkey primary key (id),
  constraint Productos_id_Categoria_producto_fkey foreign KEY ("id_Categoria_producto") references "Categoria_producto" (id),
  constraint Productos_id_Receta_fkey foreign KEY ("id_Receta") references "Receta" (id),
  constraint Productos_id_Usuario_fkey foreign KEY ("id_Usuario") references "Usuarios" (id)
) TABLESPACE pg_default;

create table public."Proveedores" (
  id bigint generated by default as identity not null,
  nombre character varying(255) not null,
  direccion character varying(255) not null,
  telefono bigint not null,
  "id_Categoria_p" bigint not null,
  email character varying null,
  horario character varying null,
  hora_apertura time without time zone null,
  hora_cierre time without time zone null,
  constraint Proveedores_pkey primary key (id),
  constraint Proveedores_id_key unique (id),
  constraint Proveedores_id_Categoria_p_fkey foreign KEY ("id_Categoria_p") references "Categoria_producto" (id)
) TABLESPACE pg_default;

create table public."Receta" (
  id serial not null,
  "ids_Mps" bigint[] null,
  constraint recetas_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Tipo_Usuario" (
  id bigint generated by default as identity not null,
  nombre character varying(255) not null,
  descripcion character varying(255) not null,
  constraint Tipo_Usuario_pkey primary key (id)
) TABLESPACE pg_default;

create table public."Usuarios" (
  id bigint generated by default as identity not null,
  nombre character varying not null,
  password character varying not null,
  tipo bigint not null,
  fecha_creacion date not null,
  constraint Usuarios_pkey primary key (id),
  constraint Usuarios_tipo_fkey foreign KEY (tipo) references "Tipo_Usuario" (id)
) TABLESPACE pg_default;

create table public."Ventas" (
  id bigint generated by default as identity not null,
  "id_Productos" bigint[] not null,
  total double precision not null,
  fecha timestamp without time zone not null,
  pago double precision not null,
  cambio double precision not null,
  "id_Usuario" bigint not null,
  "id_mp_seVende" bigint null,
  metodo_pago character varying null,
  tipo_cambio double precision null,
  constraint Ventas_pkey primary key (id),
  constraint Ventas_id_key unique (id),
  constraint Ventas_id_Usuario_fkey foreign KEY ("id_Usuario") references "Usuarios" (id),
  constraint Ventas_id_mp_seVende_fkey foreign KEY ("id_mp_seVende") references "Materia_prima" (id)
) TABLESPACE pg_default;

-- ===================================================================
-- TABLAS PARA SISTEMA DE REPORTES
-- ===================================================================

create table public."Ventas_detalle" (
  id bigint generated by default as identity not null,
  id_venta bigint not null,
  id_producto bigint not null,
  cantidad integer not null,
  precio_unitario double precision not null,
  subtotal double precision not null,
  constraint Ventas_detalle_pkey primary key (id),
  constraint Ventas_detalle_id_venta_fkey foreign key (id_venta) references "Ventas" (id) ON DELETE CASCADE,
  constraint Ventas_detalle_id_producto_fkey foreign key (id_producto) references "Productos" (id)
) TABLESPACE pg_default;

create table public."Reportes_diarios" (
  id bigint generated by default as identity not null,
  fecha date not null,
  total_ventas double precision not null default 0,
  numero_ventas integer not null default 0,
  total_compras double precision not null default 0,
  numero_compras integer not null default 0,
  productos_vendidos integer not null default 0,
  ticket_promedio double precision not null default 0,
  fecha_actualizacion timestamp without time zone not null default now(),
  constraint Reportes_diarios_pkey primary key (id),
  constraint Reportes_diarios_fecha_unique unique (fecha)
) TABLESPACE pg_default;

create table public."Reportes_cortes" (
  id bigint generated by default as identity not null,
  id_corte bigint not null,
  id_materia_prima bigint not null,
  stock_inicial bigint not null,
  stock_final bigint not null,
  diferencia bigint not null,
  porcentaje_diferencia double precision not null,
  fecha_corte date not null,
  observaciones character varying null,
  constraint Reportes_cortes_pkey primary key (id),
  constraint Reportes_cortes_id_corte_fkey foreign key (id_corte) references "Corte_inventario" (id) ON DELETE CASCADE,
  constraint Reportes_cortes_id_mp_fkey foreign key (id_materia_prima) references "Materia_prima" (id)
) TABLESPACE pg_default;